name: brunounky_movie
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  provider: ^6.1.5
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 
  json_serializable: ^6.9.5
  build_runner: ^2.4.11 

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/